engines:
  brakeman:
    enabled: true
    checks:
      CVE_2015_3227:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  rubocop:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.haml"
  - "**.rb"
  - "**.js"
  - "**.jsx"
exclude_paths:
- config/
- coverage/
- gemfiles/
- script/
- test/
