AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'test/dummy/**/*'
    - 'lib/tuttle/ruby_prof/fast_call_stack_printer.rb'

Rails:
  Enabled: true

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 25

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  Enabled: false
  SpaceBeforeBlockParameters: false
  EnforcedStyle: no_space

Style/HashSyntax:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/StringLiterals:
  Enabled: false

Style/GuardClause:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing
