AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'test/dummy/**/*'

Rails:
  Enabled: true

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 25

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/SpaceInsideBlockBraces:
  Enabled: false
  SpaceBeforeBlockParameters: false
  EnforcedStyle: no_space

Style/HashSyntax:
  Enabled: false

