require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.7
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: disable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'gemfiles/**/*'
    - 'script/**/*'
    - 'test/dummy/**/*'
    - 'lib/tuttle/ruby_prof/fast_call_stack_printer.rb'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  Enabled: false
  SpaceBeforeBlockParameters: false
  EnforcedStyle: no_space

Metrics/ClassLength:
  Max: 200

Layout/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 40

Security/MarshalLoad:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/RescueModifier:
  Enabled: false
