language: ruby
cache: bundler
sudo: false
rvm:
  - 2.3.1
  - 2.2.5
gemfile:
  - gemfiles/rails_master.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.0.gemfile

before_install: 'rm Gemfile'
script:
  - RAILS_ENV=test bundle exec rake --trace app:db:setup test
