language: ruby
cache: bundler
rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.0
gemfile:
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
before_script: "bundle update"
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test

