language: ruby
cache: bundler
sudo: false
rvm:
  - 2.1
  - 2.2
gemfile:
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test
