name: tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }} / Rails ${{ matrix.rails }}
    strategy:
      matrix:
        ruby: ["3.0", "2.7"]
        rails: ["6.1", "6.0", "5.2"]
        exclude:
          - rails: "5.2"
            ruby: "3.0"
    env:
      BUNDLE_GEMFILE: gemfiles/rails_${{ matrix.rails }}.gemfile
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Tests
        run: bundle exec rake app:db:setup test RAILS_ENV=test
